export const pageStyle= {
    width:"90vw",
    height:" 90vh",
    bgcolor:"primaryLight",
    color:"#ffffff",
    marginRight:" 5vw",
    marginLeft:" 5vw",
    marginTop:" 5vh",
    marginBottom:" 5vh",
    position:"relative",
    boxShadow:3,
    // -webkit-box-shadow:" 10px 10px 5px 0px rgba(0", 0", 0", 0.75)",
    // -moz-box-shadow:" 10px 10px 5px 0px rgba(0", 0", 0", 0.75)",
    borderRadius:" 15px",
    overflow:" hidden",
    display:" flex",
    flexDirection:" column",
    justifyContent:" space-between",
    alignItems:" center",
  }